[rowkey]
        component.0.order=ascending
        component.0.type=integer
        component.0.format="%07lld"
[Field1.value]
        size=20
[Field2.value]
        size=20
[Field3.value]
        size=20
