UPDATE 'test/Test1' "Test1-data.txt";
pause 1;
CREATE SCANNER ON 'test/Test1'[..??] LIMIT 500;
DESTROY SCANNER;
CREATE SCANNER ON 'test/Test1'[..??] WHERE ROW = "Agamemnon";
DESTROY SCANNER;
CREATE SCANNER ON 'test/Test1'[..??] WHERE ROW >= "Agamemnon" LIMIT=5;
DESTROY SCANNER;
CREATE SCANNER ON 'test/Test1'[..??] WHERE "Agamemnon" <= ROW <= "Agamemnon";
DESTROY SCANNER;
CREATE SCANNER ON 'test/Test1'[..??] WHERE "Agamemnon" <= ROW <= "Aganice";
DESTROY SCANNER;
CREATE SCANNER ON 'test/Test1'[..??] WHERE "Agamemnon" < ROW <= "Aganice";
DESTROY SCANNER;
CREATE SCANNER ON 'test/Test1'[..??] WHERE "Agamemnon" <= ROW < "Aganice";
DESTROY SCANNER;
CREATE SCANNER ON 'test/Test1'[..??] WHERE "Agamemnon" < ROW < "Aganice";
DESTROY SCANNER;
quit;
