CREATE NAMESPACE "/offset";
USE "/offset";
DROP TABLE IF EXISTS offset_test;
CREATE TABLE offset_test (cf1, cf2, cf3);
INSERT INTO offset_test VALUES ('r1', 'cf1', 'val1.1');
INSERT INTO offset_test VALUES ('r1', 'cf2', 'val1.2');
INSERT INTO offset_test VALUES ('r1', 'cf3', 'val1.3');
INSERT INTO offset_test VALUES ('r2', 'cf1', 'val2.1');
INSERT INTO offset_test VALUES ('r2', 'cf2', 'val2.2');
INSERT INTO offset_test VALUES ('r2', 'cf3', 'val2.3');
INSERT INTO offset_test VALUES ('r3', 'cf1', 'val3.1');
INSERT INTO offset_test VALUES ('r3', 'cf2', 'val3.2');
INSERT INTO offset_test VALUES ('r3', 'cf3', 'val3.3');
INSERT INTO offset_test VALUES ('r4', 'cf1', 'val4.1');
INSERT INTO offset_test VALUES ('r4', 'cf2', 'val4.2');
INSERT INTO offset_test VALUES ('r4', 'cf3', 'val4.3');
INSERT INTO offset_test VALUES ('r5', 'cf1', 'val5.1');
INSERT INTO offset_test VALUES ('r5', 'cf2', 'val5.2');
INSERT INTO offset_test VALUES ('r5', 'cf3', 'val5.3');

SELECT * FROM offset_test;
SELECT * FROM offset_test OFFSET 1;
SELECT * FROM offset_test OFFSET 3;
SELECT * FROM offset_test OFFSET 5;
SELECT * FROM offset_test OFFSET 99;
SELECT * FROM offset_test CELL_OFFSET 1;
SELECT * FROM offset_test CELL_OFFSET 3;
SELECT * FROM offset_test CELL_OFFSET 5;
SELECT * FROM offset_test CELL_OFFSET 99;
SELECT * FROM offset_test OFFSET 1 LIMIT 1;
SELECT * FROM offset_test OFFSET 1 LIMIT 3;
SELECT * FROM offset_test OFFSET 3 LIMIT 2;
SELECT * FROM offset_test OFFSET 4 LIMIT 2;
SELECT * FROM offset_test CELL_OFFSET 1 CELL_LIMIT 1;
SELECT * FROM offset_test CELL_OFFSET 1 CELL_LIMIT 3;
SELECT * FROM offset_test CELL_OFFSET 3 CELL_LIMIT 6;
SELECT * FROM offset_test CELL_OFFSET 12 CELL_LIMIT 6;
SELECT * FROM offset_test OFFSET 1 CELL_LIMIT 1;
SELECT * FROM offset_test OFFSET 1 CELL_LIMIT 3;
SELECT * FROM offset_test OFFSET 3 CELL_LIMIT 4;
SELECT * FROM offset_test OFFSET 4 CELL_LIMIT 2;
SELECT * FROM offset_test CELL_OFFSET 3 LIMIT 1;
SELECT * FROM offset_test CELL_OFFSET 3 LIMIT 3;
SELECT * FROM offset_test CELL_OFFSET 3 LIMIT 5;
SELECT * FROM offset_test CELL_OFFSET 1 LIMIT 1;
SELECT * FROM offset_test CELL_OFFSET 1 LIMIT 2;
SELECT * FROM offset_test CELL_OFFSET 2 LIMIT 2;
SELECT * FROM offset_test OFFSET 3 CELL_LIMIT_PER_FAMILY 1 LIMIT 1;
