[rowkey]
        component.0.order=random
        component.0.type=integer
        component.0.format="%05lld"
        component.0.max=10000
[Field1]
        value.size=10
[Field2]
        value.size=10
        qualifier.type=STRING
        qualifier.size=5
        qualifier.charset=abcde
