
<h2>About this sample</h2>
<p>
This is the Hypertable microblog sample. It demonstrates how to create a 
"Twitter"-like web application based on Hypertable and PHP.
</p>
<p>
Read more about...
</p>
<p>
...the database design:<br />
<a target="_blank" href="http://code.google.com/p/hypertable/wiki/ExampleDesignTwitter">http://code.google.com/p/hypertable/wiki/ExampleDesignTwitter</a><br />
<br />
...installation and configuration instructions:<br />
<a target="_blank" href="https://github.com/cruppstahl/hypertable/wiki/Setup-PHP-microblog-sample">https://github.com/cruppstahl/hypertable/wiki/Setup-PHP-microblog-sample</a><br />
</p>
<h2>About Hypertable</h2>
<p>
Hypertable is a high performance cloud database.
</p>
<ul>
  <li>Massively scalable
  <li>C++ implementation delivers optimal performance
  <li>Modeled after Google's Bigtable, which powers 100s of Google applications and services
  <li>Hypertable Thrift interface provides seamless language support for Java, PHP, Ruby, Python, Perl, and more, so you can easily build applications in your favorite language
</ul>
<p>
Visit <a target="_blank" href="http://hypertable.com">hypertable.com</a> 
for more information about features and support offers!
</p>
