<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link rel="stylesheet" type="text/css" href="/static/styles.css">
<script src="/static/microajax.minified.js" type="text/javascript"></script>
<title>Hypertable Micro-blog sample</title>
</head>
<body>
<div id="all">
<div id="header">
	<div id="logo">
		<h1><a href="http://hypertable.com"><img src="/static/lgo-hypertable.jpg" alt="Hypertable"></a></h1>
		<p>A Micro-blog Sample</p>
	</div><!-- logo -->
	<div id="nav">
		<ul>
			<li><a href="/about">About</a></li>
			<li><a href="/index">Dashboard</a></li>
<?
  if (!Zend_Auth::getInstance()->hasIdentity()) {
?>
			<li class="last"><a href="/login">Log in/Sign in</a></li>
<?
  }
  else {
?>
			<li><a href="/login/logout">Log out</a></li>
			<li class="last"><a href="/profile">Profile</a></li>
<?
  }
?>
		</ul>
	</div><!-- nav -->
</div><!-- header -->
	<div id="contents-container">
		<div id="contents">
			<div id="fullpage">


<?php echo $this->layout()->content; ?>


<p></p><p></p>
			</div><!-- home -->
		</div><!-- contents -->
	</div><!-- contents-container -->
</div><!-- all -->
<div id="footer-container">
	<div id="footer">
		<p class="nav">
			<a href="http://hypertable.com/home">Home</a> |
			<a href="http://hypertable.com/download">Download</a> |
			<a href="http://hypertable.com/community/license">License</a> |
			<a href="http://hypertable.com/documentation">Documentation</a> |
			<a class="external" href="http://code.google.com/p/hypertable/issues/list">Bug Tracker</a> |
			<a href="http://hypertable.com/community/mailing_lists">Mailing Lists</a> |
			<a href="http://hypertable.com/blog">Blog</a>
		</p>
		<!-- . nav -->
		<p class="copy">© 2011 Hypertable. All rights reserved. Based on a design by <a href="http://www.bluecoastweb.com/" target="_blank">Blue Coast Web</a></p>
	</div><!-- footer -->
</div><!-- footer-container -->

</body></html>
