/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Client_constants.h"

namespace Hypertable { namespace ThriftGen {

const ClientConstants g_Client_constants;

ClientConstants::ClientConstants() {
}

}} // namespace

