/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Hql_constants.h"

namespace Hypertable { namespace ThriftGen {

const HqlConstants g_Hql_constants;

HqlConstants::HqlConstants() {
}

}} // namespace

