
<p>
This is the Hypertable microblog sample. It demonstrates how to create a 
"Twitter"-like web application based on Hypertable and PHP.
</p>
<h2>Please Login</h2>
<p>
If you have already created an account then use your username and password to 
log in.
</p>
<?= $this->loginForm ?>
<hr>
<h2>Please Sign up</h2>
<p>
Create a new account. The account will be created immediately. Your profile 
information is visible to other users. Email and additional information are 
not mandatory and will not be verified.
</p>
<?= $this->signupForm ?>

