drop table if exists CounterTest;
create table CounterTest (a COUNTER);
insert into CounterTest values ("row", "a", "7");
insert into CounterTest values ("row", "a", "5");
insert into CounterTest values ("row", "a", "=4");
insert into CounterTest values ("row", "a", "+3");
insert into CounterTest values ("row", "a", "+7");
insert into CounterTest values ("row", "a", "=19");
insert into CounterTest values ("row", "a", "5");
insert into CounterTest values ("row", "a", "+8");
compact type=minor table CounterTest;
pause 5;
insert into CounterTest values ("row", "a", "+32");
insert into CounterTest values ("row", "a", "=7");
insert into CounterTest values ("row", "a", "9");
select * from CounterTest into file "hql-counter-test.output.1";
compact table CounterTest;
pause 5;
select * from CounterTest into file "hql-counter-test.output.2";